name: Test - custom CIDRs

on:
  workflow_dispatch:
    inputs:
      enterprise:
        description: GitHub Enterprise
        default: goodcorp
        required: true
        
      token:
        description: GitHub token
        required: true
  
jobs:
  update_allow_list:
    name: Update Enterprise IP Allow List
    runs-on: ubuntu-20.04
    
    steps:
      - name: Mask Token
        run: |
          echo "::add-mask::${{ github.event.inputs.token }}"
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update IP Allow List
        uses: ./
        with:
          github_token: ${{ github.event.inputs.token }}
          enterprise_slug: ${{ github.event.inputs.enterprise }}
          custom_cidrs: |
            192.168.10.0/24,
            192.168.11.0/24,
            192.168.12.0/24,
          
          custom_cidrs_label: 'Testing Custom CIDRs'
  
